# Generated by Django 4.2.7 on 2025-12-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('venue_data', models.JSONField()),
                ('google_rating', models.FloatField(blank=True, null=True)),
                ('google_review_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_api_call', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cached Venue',
                'verbose_name_plural': 'Cached Venues',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['category', 'city', 'district'], name='api_cachedv_categor_56fc51_idx'), models.Index(fields=['category', 'city'], name='api_cachedv_categor_83367c_idx')],
            },
        ),
    ]
