# Generated by Django 4.2.7 on 2025-12-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cachedvenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedvenue',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cachedvenue',
            name='location_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='cachedvenue',
            index=models.Index(fields=['location_key'], name='api_cachedv_locatio_4de1e3_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedvenue',
            index=models.Index(fields=['location_key', 'last_api_call'], name='api_cachedv_locatio_eb90e0_idx'),
        ),
    ]
