# Generated by Django 4.2.17 on 2025-12-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shortlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaultMillauVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('toques', models.IntegerField(default=1)),
                ('award', models.CharField(blank=True, max_length=255, null=True)),
                ('chef', models.CharField(blank=True, max_length=255, null=True)),
                ('categories', models.JSONField(default=list)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('venue_data', models.JSONField(blank=True, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gault & Millau Venue',
                'verbose_name_plural': 'Gault & Millau Venues',
                'ordering': ['-toques', 'name'],
                'indexes': [models.Index(fields=['city', 'is_active'], name='api_gaultmi_city_5de5fb_idx'), models.Index(fields=['toques', 'is_active'], name='api_gaultmi_toques_47bb32_idx')],
            },
        ),
    ]
